version: "3.8"


services:
  nginx:
    image: nginx:stable
    container_name: nginx
    volumes:
      - ./src:/var/www/pctest
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
      - "443:443"
  php:
    container_name: php
    volumes:
      - ./src:/var/www/pctest
    build: dockerfiles/php

  composer:
    container_name: composer
    build: dockerfiles/composer
    volumes:
      - ./src:/var/www/pctest

  node:
    container_name: nodejs
    build: dockerfiles/node
    volumes:
      - ./src:/var/www/pctest
    ports:
    - "5173:5173"

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=value
  artisan:
    container_name: artisan
    build: dockerfiles/artisan
    volumes:
      - ./src:/var/www/pctest    

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "7777:8080"